version: '3.8'

services:
  spell-recognition:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: professeur-dumbledore
    ports:
      - "8888:8888"
    volumes:
      - ./src:/app/src
      - ./data:/app/data
      - ./models:/app/models
      - ./docs:/app/docs
    environment:
      - JUPYTER_ENABLE_LAB=yes
    restart: unless-stopped
    networks:
      - poudlard-network

networks:
  poudlard-network:
    driver: bridge
